### ISSUE TITLE
Release 2.x roadmap

### ISSUE THREAD

**Issue by theodorosploumis** [manystories/drupal#1]
**Drupal**

- [ ] Better Drupal profile with features and custom theme.

**Major**

- [ ] Translate UI using the [public spreadsheet](https://docs.google.com/spreadsheets/d/1Rn6OAaXnehJgxkYdA71lUQx7qzkL4ruS_h2tGgJv4G8/edit?usp=sharing)
- [ ] Remove (or alter) SPARQL entries for non Stories entities
- [ ] REST API allow for CRUD actions (and authentication with cookies)
- [ ] Use the [title](https://www.drupal.org/project/title) Drupal module to enable entity translations (for non Stories entities)

**Minor**
- [ ] Allow for website to act as an oEmbed provider
- [ ] Better oEmbed with Embed.ly (eg check with the extract api)
- [ ] SSL on login etc pages
- [ ] User profile pages (my Stories, user/*/Stories)
- [ ] Usage of the original logo (svg, png etc)
- [ ] Original typeface of the logo which is [Archer](http://www.typography.com/fonts/archer/webfonts/) (although it does not support Greek etc languages)
- [ ] Better UX for mobile (such as menus)

**Other**
- [ ] Socialize the user profiles (flag stories, create group of stories, social media like accounts)
- [ ] [Tour module](https://www.drupal.org/project/joyride) to inform users about using the website
- [ ] Custom widget to embed Stories or Stories Categories
- [ ] More examples of using the APIs through real apps at [apps.manystoriesoneheart.gr](http://apps.manystoriesoneheart.gr)
